#!/bin/bash

#SBATCH --job-name d2q9-test
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --time 00:20:00
#SBATCH --partition cpu
#SBATCH --output result.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
#! Run the executable
mpirun ./d2q9-mpi input_1024x1024.params obstacles_1024x1024.dat
